// <auto-generated />
using System;
using HiHostelFes.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HiHostelFes.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181016175907_mysqlmigration")]
    partial class mysqlmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HiHostelFes.API.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HiHostelFes.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryOfOrigin");

                    b.Property<DateTime>("DateOfArriving");

                    b.Property<DateTime>("DateOfCancellation");

                    b.Property<DateTime>("DateOfLeaving");

                    b.Property<DateTime>("DateOfReservation");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Price");

                    b.Property<int>("RoomId");

                    b.Property<bool>("customerShowedHimSelf");

                    b.Property<int>("numberOfChildren");

                    b.Property<int>("numberOfClient");

                    b.Property<int>("numberOfFemale");

                    b.Property<int>("numberOfMale");

                    b.Property<int>("numberOfNights");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HiHostelFes.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("HiHostelFes.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChambreGender");

                    b.Property<string>("NameOfChambre");

                    b.Property<string>("PhotoUrl");

                    b.Property<int>("Price");

                    b.Property<bool>("RoomStatus");

                    b.Property<int>("initialPrice");

                    b.Property<int>("numberOfBeds");

                    b.Property<string>("publicIdPhoto");

                    b.Property<int>("startingFrom");

                    b.Property<string>("typeOfChambre");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HiHostelFes.API.Models.Customer", b =>
                {
                    b.HasOne("HiHostelFes.API.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HiHostelFes.API.Models.Reservation", b =>
                {
                    b.HasOne("HiHostelFes.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HiHostelFes.API.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
